### ISSUE TITLE
ios App doesnt recieve remote stream

### ISSUE THREAD

**Issue by Reedyuk** [nubomediaTI/Kurento-iOS#2]
When i run the ios app, i can successfully connect as a user in the room and broadcast my video and audio fine to the other user(web user), but for some reason the web users remote stream doesnt show.
So i tried an iPad and iPhone connecting, that seemed to work with both audio and video but it seems to struggle with the negotiation of ICE and usually drops after a few seconds.

**Comment by maross** [comment]
@Reedyuk By using our server room we were able to have two-way communication and also view the remote stream of the peer. Is the local peer's stream correctly displayed in the demo room? 
Is `[roomManager: didAddStream: ofPeer:]` called on `NBMRoomVideoViewController`?
I also noticed that connections sometimes seem very unstable, try to connect clients to the same network to see if there are improvements. I am working to understand how to improve the stability of the connections and make sure they are restored after network errors.

**Comment by maross** [comment]
...I guess that you use your own server room , our is currently offline.

**Comment by ineed** [comment]
Yes sorry, i'm using my own server running Kurento's Demo Room Server which i have chrome connected to.

**Comment by Reedyuk** [comment]
Yes sorry, i'm using my own server running Kurento's Demo Room Server which i have chrome connected to.

**Comment by maross** [comment]
No problem, it seems to work only with Firefox and Opera..for now.
