### ISSUE TITLE
Hey, Marco Rossi

### ISSUE THREAD

**Issue by GitHubOfLeon** [nubomediaTI/Kurento-iOS#4]
Hello,Marco:
               My name is Leon and I'm a ios coder who was doing somework about Kurento.  Your project help me a lot,but i think i'll need ur help. So I hope to konw ur e-mail or something if it's convenient for you. Thank u very much.I will look forward to ur reply. Best wishes.

**Comment by maross** [comment]
Hello Leon, thank you for appreciation. 
You can use the public mailing list for questions and support:
https://groups.google.com/forum/#!forum/kurento-ios
